# Generated by Django 5.2.8 on 2025-11-24 22:43

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('guard', 'Guard')], default='guard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number_of_positions', models.IntegerField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('rules', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users_from_notifications', models.ManyToManyField(related_name='exhibitions_from_notifications', through='api.AdminNotification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='exhibition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='api.exhibition'),
        ),
        migrations.CreateModel(
            name='Guard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority_number', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('availability', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_awarded', models.DateTimeField(auto_now_add=True)),
                ('explanation', models.TextField()),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='api.guard')),
            ],
            options={
                'verbose_name_plural': 'Points',
                'ordering': ['-date_awarded'],
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='api.exhibition')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='GuardAvailablePositions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_available_positions', to='api.guard')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_available_positions', to='api.position')),
            ],
        ),
        migrations.AddField(
            model_name='guard',
            name='available_positions',
            field=models.ManyToManyField(related_name='available_guards', through='api.GuardAvailablePositions', to='api.position'),
        ),
        migrations.CreateModel(
            name='PositionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CANCELED', 'Cancelled'), ('REPLACED', 'Replaced'), ('TAKEN_AFTER_LOCKING', 'Taken After Locking')], max_length=25)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_histories', to='api.guard')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_histories', to='api.position')),
            ],
            options={
                'verbose_name_plural': 'Position Histories',
            },
        ),
        migrations.AddField(
            model_name='guard',
            name='positions_from_history',
            field=models.ManyToManyField(related_name='guards_from_history', through='api.PositionHistory', to='api.position'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_explanation', models.TextField(blank=True, null=True)),
                ('report_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.guard')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.position')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='guard',
            name='positions_from_reports',
            field=models.ManyToManyField(related_name='guards_from_reports', through='api.Report', to='api.position'),
        ),
        migrations.AddIndex(
            model_name='exhibition',
            index=models.Index(fields=['-start_date'], name='api_exhibit_start_d_7c6cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='exhibition',
            index=models.Index(fields=['name'], name='api_exhibit_name_f6e11c_idx'),
        ),
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['date_awarded'], name='api_point_date_aw_6d843f_idx'),
        ),
        migrations.AddIndex(
            model_name='point',
            index=models.Index(fields=['guard', 'date_awarded'], name='api_point_guard_i_db1183_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['date', 'start_time'], name='api_positio_date_f02971_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['exhibition', 'date'], name='api_positio_exhibit_9312dc_idx'),
        ),
        migrations.AddIndex(
            model_name='position',
            index=models.Index(fields=['date'], name='api_positio_date_5e6adc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guardavailablepositions',
            unique_together={('guard', 'position')},
        ),
        migrations.AddIndex(
            model_name='positionhistory',
            index=models.Index(fields=['position', 'action_time'], name='api_positio_positio_d369b0_idx'),
        ),
        migrations.AddIndex(
            model_name='positionhistory',
            index=models.Index(fields=['guard', 'action_time'], name='api_positio_guard_i_8f09c5_idx'),
        ),
        migrations.AddIndex(
            model_name='positionhistory',
            index=models.Index(fields=['action'], name='api_positio_action_e311c8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['created_at'], name='api_report_created_a754a8_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['guard', 'created_at'], name='api_report_guard_i_6b8ec1_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['position', 'created_at'], name='api_report_positio_241765_idx'),
        ),
    ]
