# Generated by Django 5.2.8 on 2025-11-25 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_managers_remove_user_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_for_assignments', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='Day of the week when assignments are published')),
                ('time_of_assignments', models.TimeField(default='09:00', help_text='Time when assignments are published')),
                ('points_life_days', models.IntegerField(default=365, help_text='Number of days before points expire')),
                ('minimal_number_of_positions_in_week', models.IntegerField(default=2, help_text='Minimum positions a guard must take per week')),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='adminnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Admin Notification', 'verbose_name_plural': 'Admin Notifications'},
        ),
        migrations.AlterModelOptions(
            name='guardavailablepositions',
            options={'verbose_name': 'Guard Available Position', 'verbose_name_plural': 'Guard Available Positions'},
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='exhibition',
            field=models.ForeignKey(blank=True, help_text='Related exhibition (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='api.exhibition'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='number_of_positions',
            field=models.IntegerField(help_text='Total number of guard positions needed'),
        ),
        migrations.AlterField(
            model_name='exhibition',
            name='rules',
            field=models.TextField(blank=True, help_text='Special rules or instructions for this exhibition', null=True),
        ),
        migrations.AlterField(
            model_name='guard',
            name='availability',
            field=models.IntegerField(blank=True, help_text='Availability score for scheduling', null=True),
        ),
        migrations.AlterField(
            model_name='guard',
            name='priority_number',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Priority ranking for assignment algorithm', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='guardavailablepositions',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Calculated suitability score for this guard-position match', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='point',
            name='explanation',
            field=models.TextField(help_text='Reason for awarding/deducting points'),
        ),
        migrations.AlterField(
            model_name='point',
            name='points',
            field=models.DecimalField(decimal_places=2, help_text='Point value (can be positive or negative)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='report',
            name='position_explanation',
            field=models.TextField(blank=True, help_text='Additional context about the position', null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_text',
            field=models.TextField(help_text='Main report content'),
        ),
    ]
