# Generated by Django 5.2.8 on 2025-11-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_systemsettings_alter_adminnotification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='points_life_days',
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='points_life_weeks',
            field=models.IntegerField(default=4, help_text='Number of weeks before points expire'),
        ),
    ]
