# Generated by Django 5.2.8 on 2025-11-27 21:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_systemsettings_points_life_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guard', to=settings.AUTH_USER_MODEL),
        ),
    ]
