# Generated by Django 5.2.8 on 2025-12-01 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_guard_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='award_for_cancelled_position_jumping_in_before_position_day',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points awarded for jumping in on a cancelled position before the position day', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='award_for_cancelled_position_jumping_in_on_position_day',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='Points awarded for jumping in on a cancelled position on the position day', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='award_for_position_completion',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points awarded for completing a position', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='award_for_sunday_position_done',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Points for completing a Sunday position', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='day_for_start_of_configuration',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6, help_text='Day of the week when configuration starts'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='penalty_for_assigning_less_then_minimal_positions',
            field=models.DecimalField(decimal_places=2, default=-2.0, help_text='Points deducted for assigning fewer than minimal positions', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='penalty_for_being_late_with_notification',
            field=models.DecimalField(decimal_places=2, default=-2.0, help_text='Points deducted for being late with notification', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='penalty_for_being_late_without_notification',
            field=models.DecimalField(decimal_places=2, default=-5.0, help_text='Points deducted for being late without notification', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='penalty_for_position_cancellation_before_the_position_day',
            field=models.DecimalField(decimal_places=2, default=-2.5, help_text='Points deducted for canceling a position before the position day', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='penalty_for_position_cancellation_on_the_position_day',
            field=models.DecimalField(decimal_places=2, default=-5.0, help_text='Points deducted for canceling a position on the position day', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='time_of_start_of_configuration',
            field=models.TimeField(default='18:00', help_text='Time when configuration starts'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='day_for_assignments',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, help_text='Day of the week when assignments are published'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='minimal_number_of_positions_in_week',
            field=models.IntegerField(default=1, help_text='Minimum positions a guard must take per week'),
        ),
        migrations.CreateModel(
            name='GuardExhibitionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.PositiveIntegerField(help_text='Order of preference: 1 = most preferred, 2 = second, etc.')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('exhibition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_preferences', to='api.exhibition')),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exhibition_preferences', to='api.guard')),
            ],
            options={
                'verbose_name': 'Guard Exhibition Preference',
                'verbose_name_plural': 'Guard Exhibition Preferences',
                'ordering': ['guard', 'ordinal_number'],
                'indexes': [models.Index(fields=['guard', 'ordinal_number'], name='api_guardex_guard_i_ac6ad7_idx'), models.Index(fields=['created_at'], name='api_guardex_created_e7b242_idx')],
                'unique_together': {('guard', 'exhibition')},
            },
        ),
        migrations.CreateModel(
            name='GuardPositionPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal_number', models.PositiveIntegerField(help_text='Order of preference: 1 = most preferred, 2 = second, etc.')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_preferences', to='api.guard')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guard_preferences', to='api.position')),
            ],
            options={
                'verbose_name': 'Guard Position Preference',
                'verbose_name_plural': 'Guard Position Preferences',
                'ordering': ['guard', 'ordinal_number'],
                'indexes': [models.Index(fields=['guard', 'ordinal_number'], name='api_guardpo_guard_i_f1edfb_idx'), models.Index(fields=['created_at'], name='api_guardpo_created_e4758f_idx')],
                'unique_together': {('guard', 'position')},
            },
        ),
    ]
