# Generated by Django 5.2.8 on 2026-01-07 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_systemsettings_award_for_cancelled_position_jumping_in_before_position_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuardDayPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week: 0=Monday, 6=Sunday')),
                ('ordinal_number', models.PositiveIntegerField(help_text='Order of preference: 1 = most preferred, 2 = second, etc.')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_preferences', to='api.guard')),
            ],
            options={
                'verbose_name': 'Guard Day Preference',
                'verbose_name_plural': 'Guard Day Preferences',
                'ordering': ['guard', 'ordinal_number'],
            },
        ),
        migrations.DeleteModel(
            name='GuardPositionPreference',
        ),
        migrations.AddIndex(
            model_name='guarddaypreference',
            index=models.Index(fields=['guard', 'ordinal_number'], name='api_guardda_guard_i_3d0ecd_idx'),
        ),
        migrations.AddIndex(
            model_name='guarddaypreference',
            index=models.Index(fields=['created_at'], name='api_guardda_created_d6f49d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guarddaypreference',
            unique_together={('guard', 'day_of_week')},
        ),
    ]
