# Generated by Django 5.2.8 on 2026-01-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_guarddaypreference_delete_guardpositionpreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='weekday_afternoon_end',
            field=models.TimeField(default='19:00', help_text='Afternoon shift end time for weekdays'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weekday_afternoon_start',
            field=models.TimeField(default='15:00', help_text='Afternoon shift start time for weekdays'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weekday_morning_end',
            field=models.TimeField(default='15:00', help_text='Morning shift end time for weekdays'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weekday_morning_start',
            field=models.TimeField(default='11:00', help_text='Morning shift start time for weekdays'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weekend_afternoon_end',
            field=models.TimeField(default='18:00', help_text='Afternoon shift end time for weekends'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weekend_afternoon_start',
            field=models.TimeField(default='14:30', help_text='Afternoon shift start time for weekends'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weekend_morning_end',
            field=models.TimeField(default='14:30', help_text='Morning shift end time for weekends'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='weekend_morning_start',
            field=models.TimeField(default='11:00', help_text='Morning shift start time for weekends'),
        ),
    ]
