# Generated by Django 5.2.8 on 2026-01-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_systemsettings_weekday_afternoon_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='availability_updated_at',
            field=models.DateTimeField(blank=True, help_text='Last time availability was updated', null=True),
        ),
        migrations.AlterField(
            model_name='guard',
            name='availability',
            field=models.IntegerField(blank=True, help_text='Number of shifts guard is available for next week', null=True),
        ),
    ]
