# Generated by Django 5.2.8 on 2026-01-09 15:26

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_guard_availability_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonWorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_full_day', models.BooleanField(default=True, help_text='If True, entire day is non-working. If False, only one shift.')),
                ('non_working_shift', models.CharField(blank=True, choices=[('MORNING', 'Morning'), ('AFTERNOON', 'Afternoon')], help_text='Which shift is non-working (only if is_full_day=False)', max_length=10, null=True)),
                ('reason', models.TextField(blank=True, help_text='Reason for non-working day (holiday, maintenance, etc.)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AlterModelOptions(
            name='guardavailablepositions',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guard Available Position', 'verbose_name_plural': 'Guard Available Positions'},
        ),
        migrations.AlterModelOptions(
            name='systemsettings',
            options={'ordering': ['-created_at'], 'verbose_name': 'System Settings', 'verbose_name_plural': 'System Settings'},
        ),
        migrations.AlterUniqueTogether(
            name='guardavailablepositions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this is the current active version'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Admin who made this update', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_settings_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='workdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), default=list, help_text='Days of the week when museum is open (e.g., [1, 2, 3, 4, 5] for Mon-Fri)', size=None),
        ),
        migrations.AddIndex(
            model_name='guardavailablepositions',
            index=models.Index(fields=['guard', 'position', 'created_at'], name='api_guardav_guard_i_1af434_idx'),
        ),
        migrations.AddIndex(
            model_name='guardavailablepositions',
            index=models.Index(fields=['created_at'], name='api_guardav_created_99de18_idx'),
        ),
        migrations.AddField(
            model_name='nonworkingday',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='non_working_days_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='nonworkingday',
            index=models.Index(fields=['date'], name='api_nonwork_date_d8daac_idx'),
        ),
    ]
