# Generated by Django 5.2.8 on 2026-01-09 15:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_nonworkingday_alter_guardavailablepositions_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='workdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), default=[1, 2, 3, 4, 5, 6], help_text='Days of the week when museum is open for visitors', size=None),
        ),
    ]
