# Generated by Django 5.2.8 on 2026-01-09 15:37

import api.api_models.system_settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_systemsettings_workdays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='workdays',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), default=api.api_models.system_settings.default_workdays, help_text='Days of the week when museum is open for visitors', size=None),
        ),
    ]
