# Generated by Django 5.2.8 on 2026-01-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_systemsettings_workdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='day_for_end_of_configuration',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, help_text='Day of the week when configuration ends'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='next_week_end',
            field=models.DateField(blank=True, help_text='End date of next week period (set by weekly task)', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='next_week_start',
            field=models.DateField(blank=True, help_text='Start date of next week period (set by weekly task)', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='position_generation_day',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=6, help_text='Day of the week when positions are automatically generated'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='position_generation_time',
            field=models.TimeField(default='00:00', help_text='Time when positions are automatically generated'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='time_of_end_of_configuration',
            field=models.TimeField(default='20:00', help_text='Time when configuration ends'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='time_of_assignments',
            field=models.TimeField(default='21:00', help_text='Time when assignments are published'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='time_of_start_of_configuration',
            field=models.TimeField(default='20:00', help_text='Time when configuration starts'),
        ),
    ]
