# Generated by Django 5.2.8 on 2026-01-09 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_systemsettings_day_for_end_of_configuration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='position_generation_day',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='position_generation_time',
        ),
    ]
