# Generated by Django 5.2.8 on 2026-01-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_systemsettings_position_generation_day_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='day_for_end_of_configuration',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='day_for_start_of_configuration',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='time_of_end_of_configuration',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='time_of_start_of_configuration',
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='day_for_assignments',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=2, help_text='Day when automated assignments are published (after this, manual assignment period starts)'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='time_of_assignments',
            field=models.TimeField(default='21:00', help_text='Time when automated assignments are published'),
        ),
    ]
