# Generated by Django 5.2.8 on 2026-01-12 16:12

import api.api_models.schedule
import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models
from datetime import time


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_systemsettings_day_for_end_of_configuration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guard',
            name='available_positions',
        ),
        migrations.AddField(
            model_name='exhibition',
            name='open_on',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), default=list, help_text='Days of the week when this exhibition is open (subset of museum workdays)', size=None),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='time_of_assignments',
            field=models.TimeField(default=time(19, 0), help_text='Time when automated assignments are published'),
        ),
        migrations.CreateModel(
            name='GuardWorkPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Day of the week (0=Monday, 6=Sunday)')),
                ('shift_type', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], help_text='Type of shift (morning or afternoon)', max_length=10)),
                ('is_template', models.BooleanField(default=False, help_text='If true, this period is saved for future weeks')),
                ('next_week_start', models.DateField(blank=True, help_text='Start date of the week this period applies to (null if template)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_periods', to='api.guard')),
            ],
            options={
                'verbose_name': 'Guard Work Period',
                'verbose_name_plural': 'Guard Work Periods',
                'ordering': ['guard', 'day_of_week', 'shift_type'],
                'indexes': [models.Index(fields=['guard', 'is_template'], name='api_guardwo_guard_i_ac3d76_idx'), models.Index(fields=['guard', 'next_week_start'], name='api_guardwo_guard_i_72aa82_idx'), models.Index(fields=['guard', 'day_of_week', 'shift_type'], name='api_guardwo_guard_i_89313d_idx')],
            },
        ),
    ]
