# Generated by Django 5.2.8 on 2026-01-15 16:55

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_positionhistory_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyRateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hourly_rate', models.DecimalField(decimal_places=2, help_text='Hourly pay rate (€/hour)', max_digits=6)),
                ('effective_from', models.DateTimeField(help_text='When this rate became effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Hourly Rate History',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PositionSwapRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Request expires at position start time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Position Swap Request',
                'verbose_name_plural': 'Position Swap Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='guarddaypreference',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guard Day Preference', 'verbose_name_plural': 'Guard Day Preferences'},
        ),
        migrations.AlterModelOptions(
            name='guardexhibitionpreference',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guard Exhibition Preference', 'verbose_name_plural': 'Guard Exhibition Preferences'},
        ),
        migrations.RemoveIndex(
            model_name='guarddaypreference',
            name='api_guardda_guard_i_3d0ecd_idx',
        ),
        migrations.RemoveIndex(
            model_name='guardexhibitionpreference',
            name='api_guardex_guard_i_ac6ad7_idx',
        ),
        migrations.RenameField(
            model_name='systemsettings',
            old_name='award_for_sunday_position_done',
            new_name='award_for_sunday_position_completion',
        ),
        migrations.AlterUniqueTogether(
            name='guarddaypreference',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='guardexhibitionpreference',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='adminnotification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='exhibition',
            name='users_from_notifications',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='award_for_cancelled_position_jumping_in_before_position_day',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='award_for_cancelled_position_jumping_in_on_position_day',
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='cast_type',
            field=models.CharField(choices=[('broadcast', 'Broadcast - Svi korisnici'), ('unicast', 'Unicast - Specifičan korisnik'), ('multicast', 'Multicast - Grupa čuvara na pozicijama')], default='broadcast', help_text='How notification is distributed: broadcast (all), unicast (one user), multicast (group)', max_length=10),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Admin who created this notification (null for system-generated)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='When notification expires. If not set, auto-calculated: notification_date end of day OR created_at + 30 days', null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='notification_date',
            field=models.DateField(blank=True, help_text='Date for multicast filtering (required for multicast)', null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='shift_type',
            field=models.CharField(blank=True, choices=[('morning', 'Jutarnja smjena'), ('afternoon', 'Popodnevna smjena')], help_text='Shift for multicast filtering (optional, narrows down target group)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='title',
            field=models.CharField(default='Obavijest', help_text='Short notification title', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='to_user',
            field=models.ForeignKey(blank=True, help_text='Target user for unicast notifications', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guarddaypreference',
            name='day_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')]), default=[], help_text='Ordered array of days (0=Mon, 6=Sun, first = most preferred)', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guarddaypreference',
            name='is_template',
            field=models.BooleanField(default=False, help_text='If true, preferences saved for future weeks (validated weekly)'),
        ),
        migrations.AddField(
            model_name='guarddaypreference',
            name='next_week_start',
            field=models.DateField(blank=True, help_text='Start date of week these preferences apply to (null if template)', null=True),
        ),
        migrations.AddField(
            model_name='guardexhibitionpreference',
            name='exhibition_order',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[], help_text='Ordered array of exhibition IDs (first = most preferred)', size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardexhibitionpreference',
            name='is_template',
            field=models.BooleanField(default=False, help_text='If true, preferences saved for future weeks (validated weekly)'),
        ),
        migrations.AddField(
            model_name='guardexhibitionpreference',
            name='next_week_start',
            field=models.DateField(blank=True, help_text='Start date of week these preferences apply to (null if template)', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='award_for_jumping_in_on_cancelled_position',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Points awarded for jumping in on a cancelled position', max_digits=5),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=6.56, help_text='Hourly pay rate for guards (€/hour)', max_digits=6),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='this_week_end',
            field=models.DateField(blank=True, help_text='End date of current active week (set by weekly task)', null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='this_week_start',
            field=models.DateField(blank=True, help_text='Start date of current active week (set by weekly task)', null=True),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='exhibition',
            field=models.ForeignKey(blank=True, help_text='Exhibition for multicast filtering (optional, narrows down target group)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_notifications', to='api.exhibition'),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='message',
            field=models.TextField(help_text='Notification message/content'),
        ),
        migrations.AlterField(
            model_name='guarddaypreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='guardexhibitionpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='positionhistory',
            name='action',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('CANCELED', 'Cancelled'), ('REPLACED', 'Replaced'), ('SWAPPED', 'Swapped')], max_length=25),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='penalty_for_being_late_without_notification',
            field=models.DecimalField(decimal_places=2, default=-6.0, help_text='Points deducted for being late without notification', max_digits=5),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['cast_type'], name='api_adminno_cast_ty_399791_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['notification_date', 'shift_type'], name='api_adminno_notific_9dfbe5_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['to_user'], name='api_adminno_to_user_897f63_idx'),
        ),
        migrations.AddIndex(
            model_name='adminnotification',
            index=models.Index(fields=['expires_at'], name='api_adminno_expires_c52829_idx'),
        ),
        migrations.AddIndex(
            model_name='guarddaypreference',
            index=models.Index(fields=['guard', 'is_template'], name='api_guardda_guard_i_a90d40_idx'),
        ),
        migrations.AddIndex(
            model_name='guarddaypreference',
            index=models.Index(fields=['guard', 'next_week_start'], name='api_guardda_guard_i_e780f8_idx'),
        ),
        migrations.AddIndex(
            model_name='guardexhibitionpreference',
            index=models.Index(fields=['guard', 'is_template'], name='api_guardex_guard_i_180163_idx'),
        ),
        migrations.AddIndex(
            model_name='guardexhibitionpreference',
            index=models.Index(fields=['guard', 'next_week_start'], name='api_guardex_guard_i_029379_idx'),
        ),
        migrations.AddField(
            model_name='hourlyratehistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, help_text='Admin who changed the rate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hourly_rate_changes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='positionswaprequest',
            name='accepted_by_guard',
            field=models.ForeignKey(blank=True, help_text='Guard who accepted the swap', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_requests_accepted', to='api.guard'),
        ),
        migrations.AddField(
            model_name='positionswaprequest',
            name='position_offered_in_return',
            field=models.ForeignKey(blank=True, help_text='Position that accepting guard gave in return', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='swap_offers', to='api.position'),
        ),
        migrations.AddField(
            model_name='positionswaprequest',
            name='position_to_swap',
            field=models.ForeignKey(help_text='Position that requesting guard wants to swap away', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests', to='api.position'),
        ),
        migrations.AddField(
            model_name='positionswaprequest',
            name='requesting_guard',
            field=models.ForeignKey(help_text='Guard requesting to swap their position', on_delete=django.db.models.deletion.CASCADE, related_name='swap_requests_made', to='api.guard'),
        ),
        migrations.RemoveField(
            model_name='guarddaypreference',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='guarddaypreference',
            name='ordinal_number',
        ),
        migrations.RemoveField(
            model_name='guardexhibitionpreference',
            name='exhibition',
        ),
        migrations.RemoveField(
            model_name='guardexhibitionpreference',
            name='ordinal_number',
        ),
        migrations.AddIndex(
            model_name='hourlyratehistory',
            index=models.Index(fields=['-effective_from'], name='api_hourlyr_effecti_bd887d_idx'),
        ),
        migrations.AddIndex(
            model_name='positionswaprequest',
            index=models.Index(fields=['status', 'expires_at'], name='api_positio_status_50f04b_idx'),
        ),
        migrations.AddIndex(
            model_name='positionswaprequest',
            index=models.Index(fields=['requesting_guard', 'status'], name='api_positio_request_7ce18d_idx'),
        ),
        migrations.AddIndex(
            model_name='positionswaprequest',
            index=models.Index(fields=['position_to_swap'], name='api_positio_positio_769093_idx'),
        ),
        migrations.AddConstraint(
            model_name='positionswaprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('requesting_guard',), name='one_active_swap_per_guard'),
        ),
    ]
