# Generated by Django 5.2.8 on 2026-01-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_hourlyratehistory_positionswaprequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibition',
            name='event_end_time',
            field=models.TimeField(blank=True, help_text='End time for special event (required if is_special_event=True)', null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='event_start_time',
            field=models.TimeField(blank=True, help_text='Start time for special event (required if is_special_event=True)', null=True),
        ),
        migrations.AddField(
            model_name='exhibition',
            name='is_special_event',
            field=models.BooleanField(default=False, help_text='True if this is a one-time special event (opening, special occasion), False for regular exhibitions'),
        ),
    ]
