# Generated by Django 5.2.8 on 2026-01-20 11:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_exhibition_event_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('BULK_UPDATE', 'Bulk Updated'), ('BULK_DELETE', 'Bulk Deleted')], help_text='Type of action performed', max_length=20)),
                ('model_name', models.CharField(help_text="Name of the model that was changed (e.g., 'Exhibition', 'SystemSettings')", max_length=100)),
                ('object_id', models.CharField(blank=True, help_text='ID of the object that was changed (null for bulk operations)', max_length=255, null=True)),
                ('object_repr', models.CharField(help_text="String representation of the object (e.g., 'Ancient Egypt Exhibition')", max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, help_text="Dictionary of field changes: {'field_name': {'old': ..., 'new': ...}}")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user who made the change', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='User agent string (browser/app info)')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='When the action was performed')),
                ('user', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_auditlo_timesta_96ac8f_idx'), models.Index(fields=['user', '-timestamp'], name='api_auditlo_user_id_6b4e90_idx'), models.Index(fields=['model_name', '-timestamp'], name='api_auditlo_model_n_24aea3_idx'), models.Index(fields=['model_name', 'object_id'], name='api_auditlo_model_n_a07f72_idx')],
            },
        ),
    ]
