# Generated by Django 5.2.8 on 2026-01-28 18:19

import api.api_models.schedule
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0020_auditlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="position_explanation",
        ),
        migrations.AlterField(
            model_name="exhibition",
            name="open_on",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(
                    choices=[
                        (0, "Monday"),
                        (1, "Tuesday"),
                        (2, "Wednesday"),
                        (3, "Thursday"),
                        (4, "Friday"),
                        (5, "Saturday"),
                        (6, "Sunday"),
                    ]
                ),
                default=api.api_models.schedule.default_open_days,
                help_text="Days of the week when this exhibition is open (subset of museum workdays)",
                size=None,
            ),
        ),
    ]
