# Generated by Django 5.2.8 on 2026-02-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_remove_report_position_explanation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_mobile_login",
            field=models.DateTimeField(
                blank=True,
                help_text="Last login via mobile app (JWT authentication)",
                null=True,
                verbose_name="last mobile login",
            ),
        ),
    ]
